# Generated by Django 4.2.3 on 2023-07-13 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('custom_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('summary', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar')),
            ],
        ),
    ]
