# Generated by Django 4.2.3 on 2023-07-13 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='name',
            new_name='summary',
        ),
    ]
